name: CommandManager
version: 1.0
main: org.mooner.commandmanager.CommandManager
api-version: 1.18
depend:
  - BungeeAPI
  - ShopChest-1.18

commands:
  reloadcommand:
    usage: "/reloadcommand"
    aliases:
      - rc
  spawn:
    usage: "/spawn"
    aliases:
      - 스폰
      - 넴주
      - tmvhs
  tutorial:
    aliases:
      - xbxhfldjf
      - 튜토리얼
  hat:
    usage: "/hat"
    aliases:
      - 모자
      - ahwk