name: CommandManager
version: 1.0
main: org.mooner.commandmanager.CommandManager
api-version: 1.18
depend:
  - BungeeAPI
  - ShopChest-1.18
  - MoonerEco

commands:
  reloadcommand:
    usage: "/reloadcommand"
    aliases:
      - rc
  spawn:
    usage: "/spawn"
    aliases:
      - 스폰
      - 넴주
      - tmvhs
  survival:
    usage: "/survival"
    aliases:
      - 야생
      - ditod
      - 서바이벌
      - tjqkdlqjf
  상점:
    usage: "/상점"
    aliases:
      - tkdwja
  tutorial:
    aliases:
      - xbxhfldjf
      - 튜토리얼
  hat:
    usage: "/hat"
    aliases:
      - 모자
      - ahwk
  reboot:
    permission: command.reboot
  command:
    permission: command.command
    aliases:
      - cmd